name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install Poetry via pip
      run: python -m pip install poetry
    - name: Configure Poetry environment
      run: poetry config virtualenvs.create false
    - name: Clear Poetry cache
      run: poetry cache clear --all pypi
    - name: Install dependencies
      run: poetry install
    - name: Build the project
      run: poetry build
    - name: Publish distribution to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      run: poetry publish